{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kiwi-backend.fullname" . }}
  labels:
    {{- include "kiwi-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_URL: {{ .Values.secretEnv.DB_URL | quote }}
  DB_USER: {{ .Values.secretEnv.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secretEnv.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secretEnv.JWT_SECRET | quote }}
{{- end }}
